name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            sudo rm -rf /var/www/react-weather/
            sudo rm -rf /home/cloned-repo-react-weather/
            cd /var/www
            sudo mkdir react-weather
            cd /home
            sudo mkdir cloned-repo-react-weather
            cd cloned-repo-react-weather
            sudo git clone https://github.com/Andrii-Yukhymenko/weather-app.git
            cd weather-app/
            sudo yarn install
            sudo yarn build
            sudo cp -r build/* /var/www/react-weather
